/*
* generated by Xtext
*/
package org.eclipse.mylyn.docs.intent.parser.modelingunit.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ModelingUnitXTextGrammarAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/eclipse/mylyn/docs/intent/parser/modelingunit/parser/antlr/internal/InternalModelingUnitXTextGrammar.tokens");
	}
}
