/*******************************************************************************
 * Copyright (c) 2010, 2011 Obeo.

 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Obeo - initial API and implementation
 *******************************************************************************/
package org.eclipse.mylyn.docs.intent.parser.modelingunit.validation;



/**
 * Generated by Xtext, can be used to include validation on the grammar tokens.
 * 
 * @author <a href="mailto:alex.lagarde@obeo.fr">Alex Lagarde</a>
 */
public class ModelingUnitXTextGrammarJavaValidator extends AbstractModelingUnitXTextGrammarJavaValidator {

	// @Check
	// public void checkTypeNameStartsWithCapital(Type type) {
	// if (!Character.isUpperCase(type.getName().charAt(0))) {
	// warning("Name should start with a capital", MyDslPackage.TYPE__NAME);
	// }
	// }

}
