/*******************************************************************************
 * Copyright (c) 2010, 2011 Obeo.

 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Obeo - initial API and implementation
 *******************************************************************************/
package org.eclipse.mylyn.docs.intent.client.ui.editor.quickfix;

import org.eclipse.compare.CompareConfiguration;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.mylyn.docs.intent.client.ui.IntentEditorActivator;
import org.eclipse.swt.graphics.Image;

/**
 * {@link CompareConfiguration} specifying how compare editors should be displayed.
 * 
 * @author <a href="mailto:alex.lagarde@obeo.fr">Alex Lagarde</a>
 */
public class IntentCompareConfiguration extends CompareConfiguration {

	private Resource workingCopyResource;

	/**
	 * Default constructor.
	 * 
	 * @param generatedResource
	 *            the resource to compare (generated by Intent)
	 * @param workingCopyResource
	 *            the resource to compare (used by user in working copy)
	 */
	public IntentCompareConfiguration(Resource generatedResource, Resource workingCopyResource) {
		this.workingCopyResource = workingCopyResource;
	}

	/**
	 * {@inheritDoc}
	 * 
	 * @see org.eclipse.compare.CompareConfiguration#getLeftLabel(java.lang.Object)
	 */
	@Override
	public String getLeftLabel(Object element) {
		return "Intent Document";
	}

	/**
	 * {@inheritDoc}
	 * 
	 * @see org.eclipse.compare.CompareConfiguration#getLeftImage(java.lang.Object)
	 */
	@Override
	public Image getLeftImage(Object element) {
		return IntentEditorActivator.getDefault().getImage("icon/outline/document.gif");
	}

	/**
	 * {@inheritDoc}
	 * 
	 * @see org.eclipse.compare.CompareConfiguration#getRightLabel(java.lang.Object)
	 */
	@Override
	public String getRightLabel(Object element) {
		return "Working Copy (" + workingCopyResource.getURI() + ")";
	}
}
